### ISSUE TITLE
Direct songs: Artists with accent marks in the name

### ISSUE THREAD

**Issue by felipelnv** [MTG/lifesoundtrack#2]
There is a problem loading direct songs information from users when there is an artist with accent mark on the name (e.g. Jorge Sepúlveda or Antonio Machín). In this case the name of the artist is also in the title of the track, e.g. [title]=Tengo una debilidad(Antonio Machín)
This is problematic if we want to find the exact title name of that track. 
Check where the problem comes from, maybe from load_user_information ?

**Comment by Veleslavia** [comment]
Yes, you're right!
The problem is based on regexp expression for the title parsing (and the same for places etc.)
The expression '\([A-Za-z0-9\s\.\-,_]*\)$' has to be replaced with '\(.*\)$'

**Comment by felipelnv** [comment]
Oh ok!
I'll correct that expression :) Thanks!

**Comment by Veleslavia** [comment]
Actually, I corrected it yesterday eventually :)

[cc3ffd](https://github.com/MTG/lifesoundtrack/commit/cc3ffd3e9123614a58269d77f788f02954e12b71)

**Comment by felipelnv** [comment]
Thanks!
